[package]
name = "gfx-hal"
version = "0.9.0"
description = "gfx-rs hardware abstraction layer"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"
authors = ["The Gfx-rs Developers"]
documentation = "https://docs.rs/gfx-hal"
workspace = "../.."
edition = "2021"

[features]
unstable = []

[lib]
name = "gfx_hal"
path = "src/lib.rs"

[dependencies]
bitflags = "1.0"
naga = { git = "https://github.com/gfx-rs/naga", tag = "gfx-26" }
raw-window-handle = "0.3"
serde = { version = "1", features = ["serde_derive"], optional = true }
thiserror = "1"
external_memory = { path = "../external-memory", version = "0.0.1", package = "external-memory" }

[dev-dependencies]
backend-boilerplate = { path = "../backend-boilerplate", package = "backend-boilerplate", version = "0.9" }

